name: Android CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Setup Gradle wrapper
        run: |
          # Create gradle wrapper if missing
          if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
            echo "Gradle wrapper jar not found, downloading..."
            mkdir -p gradle/wrapper
            curl -L https://services.gradle.org/distributions/gradle-8.5-bin.zip -o gradle-8.5-bin.zip
            unzip gradle-8.5-bin.zip
            cp gradle-8.5/lib/gradle-wrapper-8.5.jar gradle/wrapper/gradle-wrapper.jar
            rm -rf gradle-8.5 gradle-8.5-bin.zip
          fi
      
      - name: Run tests
        run: ./gradlew test
      
      - name: Run lint
        run: ./gradlew lintDebug
      
      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug
          ls -la app/build/outputs/apk/debug/
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
